on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt install gcc-10 g++-10 cmake
    - name: Compiling IBScpp
      run: |
        mkdir -p IBScpp/build 
        cd IBScpp/build
        cmake -DCMAKE_BUILD_TYPE=Release ../ 
        make
        cd ../..
    - name: Running integration tests
      run: |
        tests/integration_cpp.sh
